# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1097ae8ce4661453d7a47047f33cc1a5cfa0603f98d43e309ec0252beee0e543978b17607353f5ec1560f5c639716a7fa548534d82a50101a434e5e680d5eb2b

test:
  secret_key_base: 63ab7f712259b2360740fab4e6fe1670c6ffa916c236f3b984e10619c5ad63c05f01e80f9dacc7771149ed189f7a82be410d2e20fd4ab5a57a826ab26f18eeb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
